import type { WeeklyReport } from "@/lib/types";

export const mockWeeklyReports: WeeklyReport[] = [
  {
    id: "report-1",
    meeting_info: {
      empresa: "Arenza Logistica",
      setor: "Pos-vendas",
      data_reuniao: "2026-03-17",
      horario_inicio: "08:30",
      horario_fim: "10:10",
      participantes: ["Marina Dias", "Paulo Mendes", "Ana Ribeiro"],
      responsavel_conducao: "Marina Dias",
    },
    indicators: {
      periodo_inicio: "2026-03-10",
      periodo_fim: "2026-03-16",
      chamados_abertos_total: 8,
      chamados_fechados_total: 6,
      chamados_fora_sla: 2,
      tempo_medio_resposta: 31,
      tempo_medio_resolucao: 367,
      clientes_contatados_pos_instalacao: 5,
    },
    chamados: [
      {
        id: "call-1",
        cliente: "Arenza Logistica",
        projeto_ou_painel: "Portal do Cliente",
        descricao_problema: "Lentidao no resumo financeiro.",
        data_abertura: "2026-03-10",
        hora_abertura: "09:05",
        data_resposta: "2026-03-10",
        hora_resposta: "09:42",
        data_resolucao: "2026-03-11",
        hora_resolucao: "16:20",
        descricao_atendimento: "Otimizacao da query e ajuste de indice.",
        status: "resolvido",
      },
      {
        id: "call-2",
        cliente: "Blue Commerce",
        projeto_ou_painel: "App do Franqueado",
        descricao_problema: "Falha ao anexar comprovante.",
        data_abertura: "2026-03-11",
        hora_abertura: "13:10",
        data_resposta: "2026-03-11",
        hora_resposta: "14:20",
        data_resolucao: "",
        hora_resolucao: "",
        descricao_atendimento: "Mapeamento de bug em upload Android.",
        status: "em andamento",
      },
      {
        id: "call-3",
        cliente: "Nexa Office",
        projeto_ou_painel: "CRM Comercial",
        descricao_problema: "Divergencia na sincronizacao com ERP.",
        data_abertura: "2026-03-12",
        hora_abertura: "10:00",
        data_resposta: "2026-03-12",
        hora_resposta: "10:28",
        data_resolucao: "",
        hora_resolucao: "",
        descricao_atendimento: "Aguardando validacao de retorno do cliente.",
        status: "aguardando cliente",
      },
    ],
    mensagens_chamado: [
      {
        id: "msg-1",
        chamado_id: "call-1",
        tipo_mensagem: "cliente",
        data_mensagem: "2026-03-10",
        hora_mensagem: "09:05",
      },
      {
        id: "msg-2",
        chamado_id: "call-1",
        tipo_mensagem: "suporte",
        data_mensagem: "2026-03-10",
        hora_mensagem: "09:42",
      },
      {
        id: "msg-3",
        chamado_id: "call-2",
        tipo_mensagem: "cliente",
        data_mensagem: "2026-03-11",
        hora_mensagem: "13:10",
      },
      {
        id: "msg-4",
        chamado_id: "call-2",
        tipo_mensagem: "suporte",
        data_mensagem: "2026-03-11",
        hora_mensagem: "14:20",
      },
      {
        id: "msg-5",
        chamado_id: "call-3",
        tipo_mensagem: "cliente",
        data_mensagem: "2026-03-12",
        hora_mensagem: "10:00",
      },
      {
        id: "msg-6",
        chamado_id: "call-3",
        tipo_mensagem: "suporte",
        data_mensagem: "2026-03-12",
        hora_mensagem: "10:28",
      },
    ],
    pesquisa_satisfacao: [
      {
        id: "nps-1",
        cliente: "Arenza Logistica",
        nota: 9,
        tipo_nps: "empresa",
        comentario_cliente: "Suporte rapido e objetivo.",
      },
      {
        id: "nps-2",
        cliente: "Blue Commerce",
        nota: 7,
        tipo_nps: "vendedor",
        comentario_cliente: "Boa comunicacao, mas ainda espera correcao final.",
      },
    ],
    clientes_risco: [
      {
        id: "risk-1",
        cliente: "Blue Commerce",
        projeto_painel: "App do Franqueado",
        problema_relato: "Erro recorrente no fluxo de comprovantes.",
        proximo_passo: "Liberar hotfix e validar com franqueados piloto.",
        prazo: "2026-03-20",
        status_atual: "critico",
      },
      {
        id: "risk-2",
        cliente: "Nexa Office",
        projeto_painel: "CRM Comercial",
        problema_relato: "Dependencia de retorno do time do cliente.",
        proximo_passo: "Reuniao conjunta para homologacao.",
        prazo: "2026-03-21",
        status_atual: "andamento",
      },
    ],
    observacoes_gerais:
      "A semana exigiu concentracao maior em contas com alto impacto operacional e alinhamento mais proximo com produto.",
    instalacoes_recentes: [
      {
        id: "install-1",
        cliente: "Solar Prime",
        data_instalacao: "2026-03-14",
        contato_pos_instalacao: "Ligacao no dia seguinte",
        situacao_cliente: "Adaptacao inicial positiva",
        acoes_necessarias: "Enviar material complementar de onboarding.",
      },
    ],
    oportunidades_comerciais: [
      {
        id: "opp-1",
        cliente: "Arenza Logistica",
        tipo_oportunidade: "upgrade_painel",
        acao_sugerida: "Apresentar modulo analitico avancado.",
        responsavel: "Paulo Mendes",
        prazo: "2026-03-24",
      },
      {
        id: "opp-2",
        cliente: "Blue Commerce",
        tipo_oportunidade: "contrato_manutencao",
        acao_sugerida: "Formalizar pacote trimestral de sustentacao.",
        responsavel: "Marina Dias",
        prazo: "2026-03-26",
      },
    ],
    dificuldades: {
      principais_dificuldades:
        "Atrasos de homologacao e dependencias com areas externas do cliente.",
      gargalo_comercial: "Repasse tardio de contexto ao suporte.",
      gargalo_instalacao: "Checklist manual incompleto em duas contas novas.",
      gargalo_suporte_tecnico: "Fila N2 pressionada por incidentes simultaneos.",
      gargalo_producao: "Tempo de ajuste acima do previsto em uma release.",
      gargalo_financeiro: "Negociacoes travadas por pendencias contratuais.",
      gargalo_outro: "Capacitacao insuficiente em parte da base.",
      sugestao_melhoria_processo:
        "Criar ritual fixo de handoff comercial > implantacao > suporte.",
    },
    acoes_melhoria: [
      {
        id: "act-1",
        acao: "Padronizar checklists de onboarding.",
        responsavel: "Ana Ribeiro",
        prazo: "2026-03-23",
        status: "andamento",
      },
      {
        id: "act-2",
        acao: "Definir regra de escalonamento por criticidade.",
        responsavel: "Marina Dias",
        prazo: "2026-03-25",
        status: "pendente",
      },
    ],
    prioridades_proxima_semana: [
      "Encerrar incidentes criticos da Blue Commerce.",
      "Homologar integracao da Nexa Office.",
      "Executar follow-up com instalacoes recentes.",
      "Formalizar oportunidades de upgrade abertas.",
      "Revisar SLA interno de triagem.",
    ],
    contato_proativo: [
      {
        id: "contact-1",
        cliente: "Solar Prime",
        tipo_contato: "ligacao",
      },
      {
        id: "contact-2",
        cliente: "Arenza Logistica",
        tipo_contato: "whatsapp",
      },
    ],
    resumo_final: {
      pontos_positivos_semana:
        "Boa reducao do backlog e melhora na velocidade da primeira resposta.",
      pontos_atencao:
        "Ainda existem contas sob risco por homologacao lenta e dependencias externas.",
    },
    registro_ata: {
      responsavel_registro: "Marina Dias",
      supervisor_pos_vendas: "Felipe Castro",
      gestor: "William Melo",
      cidade: "Sao Paulo",
      data_ata: "2026-03-17",
    },
  },
];
